config:
  output_file: './repos.csv'
  compute_statistics: off 

rules:
  js:
    - '@polkadot filename:package.json' # matching polkadot JS api
    - '@talisman filename:package.json' # matching talisman wallet integration
	
  rust:
    - 'frame filename:Cargo.toml' # project uses frame
